apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: managed-cert
spec:
  domains:
    - botstudio.tech
    - answers-ai-assistants-stuc-concurrent.nl
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: managed-cert-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: global-ip
    networking.gke.io/managed-certificates: managed-cert
    kubernetes.io/ingress.class: "gce"
spec:
  defaultBackend:
    service:
      name: mc-service
      port:
        number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mc-service
spec:
  selector:
    app: mc-service
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
{{/*---*/}}
{{/*apiVersion: apps/v1*/}}
{{/*kind: Deployment*/}}
{{/*metadata:*/}}
{{/*  name: helloweb*/}}
{{/*  labels:*/}}
{{/*    app: mc-service*/}}
{{/*spec:*/}}
{{/*  selector:*/}}
{{/*    matchLabels:*/}}
{{/*      app: hello*/}}
{{/*      tier: web*/}}
{{/*  template:*/}}
{{/*    metadata:*/}}
{{/*      labels:*/}}
{{/*        app: hello*/}}
{{/*        tier: web*/}}
{{/*    spec:*/}}
{{/*      containers:*/}}
{{/*      - name: hello-app*/}}
{{/*        image: us-docker.pkg.dev/google-samples/containers/gke/hello-app:1.0*/}}
{{/*        ports:*/}}
{{/*        - containerPort: 8080*/}}
{{/*        resources:*/}}
{{/*          requests:*/}}
{{/*            cpu: 200m*/}}
{{/*---*/}}